name: RUN Rspec
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Bundle install
        run: bundle install
      - name: DB setup
        run: bundle exec rails db:setup
      - name: Run rspec
        run: rails spec
