name: RUN Rspec
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432

    steps:
      - name: check out code
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: setup node.js 15.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.4.0
      - name: chache Gemfile.lock
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: chache yarn.lock
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        run: yarn install
      - name: Build
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.yml.github-actions config/database.yml
          gem install bundler
          bundle install --path vendor/bundle --jobs 4
          bundle exec rails db:setup
          rails -v
