name: RUN Rspec
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        ports: ['5432:5432']
        env:
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: setup node.js 15.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.4.0
      - name: chache Gemfile.lock
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: chache yarn.lock
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        run: yarn install
      - name: gem install bundler
        run: gem install bundler
      - name: bundle install
        run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Build
        env:
          DATABASE_URL: postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6370/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails spec
      - name: Run rspec
        run: rails spec
