name: RUN Rspec
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Bundle install
        run: bundle install
      - name: db migrate
        run: bundle exec rails db:migrate
      - name: Run rspec
        run: rails spec
