name: RUN Rspec
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: 'trust'
    container:
      image: ruby:2.6.2
      env:
        RAILS_ENV: test
        DATABASE_HOST: postgres
        REDIS_URL: redis://redis:6379/1

    steps:
      - name: Cache bundle gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ env.cache-name }}-
            ${{ runner.os }}-gem-
            ${{ runner.os }}-
      - name: Install Bundler
        run: gem install bundler
      - name: Bundle install
        run: bundle install
      - name: DB setup
        run: bundle exec rails db:setup
      - name: Run rspec
        run: bundle exec rspec
